spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: quiz-service
          uri: lb://quiz-service
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=1
        - id: posts
          uri: lb://posts
          predicates:
            - Path=/api/v1/posts/**
          filters:
            - StripPrefix=0
        - id: comments
          uri: lb://comments
          predicates:
            - Path=/api/v1/comments/**
          filters:
            - StripPrefix=0
        - id: collaborations-service
          uri: lb://collaborations
          predicates:
            - Path=/collaboration/**
          filters:
            - StripPrefix=0
        - id: projets-service
          uri: lb://projets
          predicates:
            - Path=/projet/**, /tache/**
          filters:
            - StripPrefix=0
        - id: Forum-service
          uri: lb://Forum
          predicates:
            - Path=/api/communities/**
          filters:
            - StripPrefix=0
        - id: categories-service
          uri: lb://categories
          predicates:
            - Path=/categorie/**
          filters:
            - StripPrefix=1
        - id: Events-service
          uri: lb://Events
          predicates:
            - Path=/participations/**, /liste-attente/**, /evenements/**, /uploads/**
          filters:
            - StripPrefix=0

server:
  port: 8222

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



