spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8000
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: stage-service
          uri: lb://stage-service
          predicates:
            - Path=/stages/**
          filters:
            - StripPrefix=1
server:
  port: 6002

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6001/eureka/



