eureka:
  instance:
    hostname: localhost  # Nom d'hôte de l'instance Eureka
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka  # URL du service Eureka
    wait-time-in-ms-when-sync-empty: 5000
server:
  port: 5010  # Port sur lequel le serveur Spring Boot écoute

spring:
  application:
    name: ressources  # Nom de l'application Spring Boot
  config:
    import: optional:configserver:http://localhost:8888  # Importation optionnelle de la configuration depuis le serveur de configuration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Classe du driver JDBC pour MySQL
    url: jdbc:mysql://localhost:3306/ressources  # URL de la base de données MySQL
    username: username  # Nom d'utilisateur pour la base de données
    password: password  # Mot de passe pour la base de données
  servlet:
    multipart:
      max-file-size: 500MB  # Taille maximale d'un fichier
      max-request-size: 500MB  # Taille maximale d'une requête entière

  jpa:
    hibernate:
      ddl-auto: update  # Stratégie de génération du schéma de la base de données (ici, création à chaque démarrage)
    database: mysql  # Type de base de données
    database-platform: org.hibernate.dialect.MySQLDialect  # Dialecte Hibernate pour MySQL$