eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 5500

spring:
  application:
    name: Events
  config:
    import: optional:configserver:http://localhost:8888

  mail:
    host: smtp.gmail.com
    port: 587
    username: roudainagmati11@gmail.com
    password: "mfjz fvtz yhlo zows"
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/events?createDatabaseIfNotExist=true
    username: root
    password:


  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
